### ISSUE TITLE
Research how to sign transactions without keeping the private key on disk

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot#167]

**Comment by krasi-georgiev** [comment]
What is the use case for this? Is this when a miner stakes TRB?

**Comment by krasi-georgiev** [comment]
After a quick talk internally we all agree that we want to explore more on how to sign transactions without keeping the private key locally. I don't think a hardware wallet is an answer here as this requires the user to press buttons for every transaction which is not practical as the software runs 24/7 and does many transactions.

I am renaming the title so we can look into more ways to achieve this.

Here is an idea:
an online vault that keeps the private key without exposing it. Anyone with the vault password can sing transactions, but will not have access to the private key. 
If the vault password is compromised it can be used to sing transactions and not to steal the private key. If someone gets access to this password the first thing they will do is create a transaction to move the funds to another account so it is debatable if this is any better. Another security measure to accessing the vault could be with IP whitelisting so that only a given IP can access the vault to sign transactions.
